### ISSUE TITLE
Subtle: Class vs. id

### ISSUE THREAD

**Issue by blerude** [annchelic/prj-rev-bwfs-dasmoto#2]
https://github.com/annchelic/prj-rev-bwfs-dasmoto/blob/master/Dasmotos/index.html#L11

In this case, you might prefer to give id selectors over class, as the stylings you're giving with those selectors are unique to those particular elements.

**Comment by annchelic** [comment]
Updated master. It is cleaner code now with the id tags instead of class divisions. Thank you for the feedback. Leaving issue open hoping you review.

**Comment by blerude** [comment]
Looks great! Glad you followed up.
