### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by blerude** [annchelic/prj-rev-bwfs-dasmoto#4]
Grade: Meets Expectations

Awesome job on this project! Your code is very easy to read and comprehend, which is hugely important as your projects grow in size and complexity and if you begin collaborating with others. Your alignment and spacing conventions are solid, as it's easy to how the HTML elements are grouped together and related. 

I attached an article outlining the difference between classes and ids, and giving some information on how to determine when to use which. I hope you find it useful! As for your CSS, it might interest you to learn about Google Fonts, a resource for finding cool fonts, and Coolors.co, a color palette generator. Both of these resources can help enhance the visual aspect of your projects and give you freedom to design things in your own style. Just some suggestions! Again, great job on this project and congratulations!

**Comment by annchelic** [comment]
I am not locating the attachment of the article you mention. Could you please advise how I access attachments?

**Comment by blerude** [comment]
Yes, my apologies. I didn't include the link. Here it is: https://css-tricks.com/the-difference-between-id-and-class/

**Comment by annchelic** [comment]
Thanks so much!
